# Generated by Django 2.0.2 on 2018-02-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='close',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='open',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='volume',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
